# Generated by Django 5.2.6 on 2025-09-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='item_quantity',
            new_name='quantity',
        ),
    ]
